apiVersion: v1
kind: Secret
metadata:
  name: employee-app-secret
type: Opaque
stringData:
  DB_HOST: "employee-app-db.c8tsqisw853g.us-east-1.rds.amazonaws.com"
  DB_USER: "admin"
  DB_PASSWORD: "Admin#123"
  DB_NAME: "employee_db"
  DB_PORT: "3306"