apiVersion: apps/v1

kind: Deployment

metadata:
  name: {{ .Release.Name }}-employee-app

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: employee-app

  template:
    metadata:
      labels:
        app: employee-app

    spec:
      containers:
        - name: employee-app

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 5000