apiVersion: v1

kind: Service

metadata:
  name: {{ .Release.Name }}-employee-app

spec:
  type: {{ .Values.service.type }}

  selector:
    app: employee-app

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
